name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  check:
    name: Check
    uses: ./.github/workflows/test.yml
    secrets: inherit

  prerelease:
    name: Prerelease
    needs: check
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      release: prerelease
