name: CI

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Test
        run: npm test

      - name: Typecheck
        run: npm run typecheck

  code-style:
    name: Code Style
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup
        uses: ./.github/actions/setup

      - name: Format
        run: npm run format

      # - name: Lint
      #   run: npm run lint

  prerelease:
    name: Prerelease
    needs: [test, code-style]
    if: github.event_name == 'push'
    uses: ./.github/workflows/release.yml
    secrets: inherit
    with:
      release: prerelease
